name: CMake build

on:
  push:
    #tags:
    #  - 'v*'         # Matches tags like v1.2.3
    branches:
      - main
      - test-workflow-2
#   pull_request:
    # branches: [ "main" ]
    
jobs:
  build_windows:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-release
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
      - uses: actions/checkout@v4

      - uses: repolevedavaj/install-nsis@v1.0.3
        with:
          nsis-version: '3.11'

      - name: Setup vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v7
        with:
          manifest-dir: '${{ github.workspace }}'
          triplet: 'x64-windows-release'
          token: '${{ github.token }}'
          cache-key: "vcpkg-action-cache"

      - name: Configure CMake
        run: cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -DSKIP_CPACK=OFF -B ${{github.workspace}}/build --preset win64-release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target package --parallel 2

      - name: Find executable
        id: find_exe
        shell: pwsh
        run: |
          $file = Get-ChildItem build/pulse-visualizer-*-win64.exe | Select-Object -First 1
          echo "file=$($file.FullName)" >> $env:GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulse-visualizer-win64-installer
          path: ${{ steps.find_exe.outputs.file }}

  build_linux:
    runs-on: ubuntu-latest

    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libfftw3-dev libfreetype-dev libglew-dev libyaml-cpp-dev ninja-build libebur128-dev libx11-dev libwayland-dev

      - name: Build SDL3 from source
        run: |
          git clone https://github.com/libsdl-org/SDL.git --branch main --depth 1
          cd SDL
          mkdir build && cd build
          cmake .. -DSDL_TEST=OFF -DSDL_STATIC=OFF
          make -j2
          sudo make install

      - name: Configure CMake
        run: cmake -DSKIP_CPACK=OFF -B ${{github.workspace}}/build --preset linux-release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target package --parallel 2

      - name: Find executable
        id: find_exe
        run: echo "file=$(ls build/pulse-visualizer-*-Linux.tar.gz)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulse-visualizer-linux-installer
          path: ${{ steps.find_exe.outputs.file }}
